steps:
  # Deploy to Cloud Run
  # - name: google/cloud-sdk
  #   args: ['gcloud', 'run', 'deploy', 'helloworld', 
  #          '--image=gcr.io/cloudrun/hello', 
  #          '--region', 'us-central1', '--platform', 'managed', 
  #          '--allow-unauthenticated']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['export']